return {}
-- return {
--   "mfussenegger/nvim-lint",
--   opts = {
--     linters_by_ft = {
--       ruby = { "rubocop" },
--       terraform = { "terraform_validate" },
--       tf = { "terraform_validate" },
--       python = { "flake8" },
--       haml = { "haml-lint" },
--     },
--   },
-- }
